// <auto-generated />
namespace WorkoutNotesApi.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixSortOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixSortOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201705152006408_FixSortOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
